name: Claim SkinsMonkey Entry

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC)
  workflow_dispatch:      # Allow manual run from GitHub interface

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install

    - name: Create auth.json from secret
      run: echo '${{ secrets.AUTH_JSON }}' > auth.json

    - name: Run claim bot
      run: python claim.py

